/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class SimpleChainTest {
    @Test public void testAppHasAGreeting() {
        SimpleChain classUnderTest = new SimpleChain();
        assertNotNull("app should have a greeting", "test");
    }
}
